### PR TITLE
add glossary module

### PR DESCRIPTION
**Pull request by yihongXU**
add a Glossary module.

### CODE REVIEW

**Review by anisayari — CHANGES_REQUESTED** [review]
Hi @yihongXU , thank you for your contribution which come from the issue #2  . Look good. 
Here my review : 
 - All new commands  have to be in `IMTA-report.cls`. In `report.tex` , only a line `\makeglossaries`should appear. And all glossary entry will be viewed. 
- We could define a glossary.tex. 
- And in a chapter to link a world with a glossaries entry use `\Glspl{word_defined_in_the-glossary}
- By default, I think make more sense, if we put the glossaries at the beginning (after the summary).

**Comment by yihongXU** [comment]
Hi, I've modified the files as requested but how can I merge to this pull request ?
I see this :
"Only those with write access to this repository can merge pull requests."

**Comment by anisayari** [comment]
And it's fine , just go on to push your commit here, they are pushed on this pull request, I will merge them with master when all is fine :) . Thank you for your contribution.

**Comment by yihongXU** [comment]
\loadglsentries{chapters/glossary} added. 
And yes, i've tested it with sharelatex, it works fine.

**Review by anisayari — APPROVED** [review]

**Comment by anisayari** [comment]
fixes #2 
closes #2

**Pull request merged**
